// quizList.js

export const javascriptQuizList = [
  {
    id: "array",
    title: "array",
    author: "배열 퀴즈",
    topic: "javascript",
    category: "code",
    subCategory: "array",
    type: "빈칸 뚫기",
  },
  {
    id: "event",
    title: "event",
    author: "이벤트 문제",
    topic: "javascript",
    category: "code",
    subCategory: "event",
    type: "빈칸 뚫기",
  },
  {
    id: "function",
    title: "function",
    author: "함수",
    topic: "javascript",
    category: "code",
    subCategory: "function",
    type: "빈칸 뚫기",
  },
  {
    id: "object",
    title: "object",
    author: "객체",
    topic: "javascript",
    category: "code",
    subCategory: "object",
    type: "빈칸 뚫기",
  },
  {
    id: "promise",
    title: "promise",
    author: "동기화 비동기",
    topic: "javascript",
    category: "code",
    subCategory: "promise",
    type: "빈칸 뚫기",
  },

  //  ////////////
  {
    id: "object",
    title: "object",
    author: "오브젝트",
    topic: "javascript",
    category: "notion",
    subCategory: "object",
    type: "4지 선다형",
  },
  {
    id: "array",
    title: "array",
    author: "배열 퀴즈",
    topic: "javascript",
    category: "notion",
    subCategory: "array",
    type: "4지 선다형",
  },
  {
    id: "promise",
    title: "promise",
    author: "동기화 비동기",
    topic: "javascript",
    category: "notion",
    subCategory: "promise",
    type: "4지 선다형",
  },
  {
    id: "basic",
    title: "basic",
    author: "기초",
    topic: "javascript",
    category: "notion",
    subCategory: "basic",
    type: "4지 선다형",
  },
  {
    id: "event",
    title: "event",
    author: "이벤트",
    topic: "javascript",
    category: "notion",
    subCategory: "event",
    type: "4지 선다형",
  },
  // ... 나머지 퀴즈 항목도 동일하게 수정
];

export const typescriptQuizList = [
  {
    id: "board",
    title: "borad",
    author: "게시판 만들기",
    topic: "typescript",
    category: "code",
    subCategory: "board",
    type: "빈칸 뚫기",
  },
  {
    id: "typescriptboards",
    title: "typescriptboards",
    author: "타입스크립트 보드",
    topic: "typescript",
    category: "code",
    subCategory: "typescriptboards",
    type: "빈칸 뚫기",
  },
  {
    id: "utilitytype",
    title: "utilitytype",
    author: "유틸리티 타입",
    topic: "typescript",
    category: "code",
    subCategory: "utilitytype",
    type: "빈칸 뚫기",
  },
  {
    id: "backenddata",
    title: "backenddata",
    author: "백엔드의 데이터 타입 지정",
    topic: "typescript",
    category: "code",
    subCategory: "backenddata",
    type: "빈칸 뚫기",
  },

  {
    id: "map",
    title: "map",
    author: "맵 함수",
    topic: "typescript",
    category: "code",
    subCategory: "map",
    type: "빈칸 뚫기",
  },
  {
    id: "Routing",
    title: "Routing",
    author: "라우팅",
    topic: "typescript",
    category: "code",
    subCategory: "Routing",
    type: "빈칸 뚫기",
  },
  {
    id: "setState",
    title: "setState",
    author: "변수 넣기",
    topic: "typescript",
    category: "code",
    subCategory: "setState",
    type: "빈칸 뚫기",
  },
  {
    id: "basic",
    title: "basic",
    author: "타입스크립트 기초",
    topic: "typescript",
    category: "code",
    subCategory: "basic",
    type: "빈칸 뚫기",
  },

  //
  //
  //
  {
    id: "board",
    title: "board",
    author: "게시판 만들기",
    topic: "typescript",
    category: "notion",
    subCategory: "board",
    type: "4지 선다형",
  },

  {
    id: "map",
    title: "map",
    author: "맵 함수",
    topic: "typescript",
    category: "notion",
    subCategory: "map",
    type: "4지 선다형",
  },
  {
    id: "Routing",
    title: "Routing",
    author: "라우팅",
    topic: "typescript",
    category: "notion",
    subCategory: "Routing",
    type: "4지 선다형",
  },
  {
    id: "Container.presenter",
    title: "Container.presenter",
    author: "컨테이너 프리젠터",
    topic: "typescript",
    category: "notion",
    subCategory: "Container.presenter",
    type: "4지 선다형",
  },
  {
    id: "basic",
    title: "basic",
    author: "타입스크립트 기초",
    topic: "typescript",
    category: "notion",
    subCategory: "basic",
    type: "4지 선다형",
  },

  // ... 나머지 퀴즈 항목도 동일하게 수정
];

export const cssQuizList = [
  {
    id: "action",
    title: "반응형",
    author: "반응형",
    topic: "css",
    category: "code",
    subCategory: "action",
    type: "빈칸 뚫기",
  },
  {
    id: "advance",
    title: "CSS심화",
    author: "CSS심화",
    topic: "css",
    category: "code",
    subCategory: "action",
    type: "빈칸 뚫기",
  },
  {
    id: "basic",
    title: "CSS기초",
    author: "CSS기초",
    topic: "css",
    category: "code",
    subCategory: "action",
    type: "빈칸 뚫기",
  },
  {
    id: "layout",
    title: "레이아웃",
    author: "레이아웃",
    topic: "css",
    category: "code",
    subCategory: "layout",
    type: "빈칸 뚫기",
  },
  {
    id: "background",
    title: "배경화면",
    author: "배경화면",
    topic: "css",
    category: "code",
    subCategory: "background",
    type: "빈칸 뚫기",
  },
  {
    id: "style",
    title: "스타일",
    author: "스타일",
    topic: "css",
    category: "code",
    subCategory: "style",
    type: "빈칸 뚫기",
  },
  {
    id: "property",
    title: "속성",
    author: "속성",
    topic: "css",
    category: "code",
    subCategory: "property",
    type: "빈칸 뚫기",
  },
  {
    id: "text",
    title: "text",
    author: "텍스트",
    topic: "css",
    category: "code",
    subCategory: "text",
    type: "빈칸 뚫기",
  },
  {
    id: "boxmodel",
    title: "박스모델",
    author: "박스모델",
    topic: "css",
    category: "code",
    subCategory: "boxmodel",
    type: "빈칸 뚫기",
  },

  // ///////////////////////
  {
    id: "action",
    title: "반응형",
    author: "반응형",
    topic: "css",
    category: "notion",
    subCategory: "action",
    type: "4지 선다형",
  },
  {
    id: "basic",
    title: "CSS기초",
    author: "CSS기초",
    topic: "css",
    category: "notion",
    subCategory: "action",
    type: "4지 선다형",
  },
  {
    id: "layout",
    title: "레이아웃",
    author: "레이아웃",
    topic: "css",
    category: "notion",
    subCategory: "layout",
    type: "4지 선다형",
  },
  {
    id: "style",
    title: "스타일",
    author: "스타일",
    topic: "css",
    category: "notion",
    subCategory: "style",
    type: "4지 선다형",
  },
  {
    id: "text",
    title: "폰트",
    author: "폰트",
    topic: "css",
    category: "notion",
    subCategory: "text",
    type: "4지 선다형",
  },
  {
    id: "boxmodel",
    title: "박스모델",
    author: "박스모델",
    topic: "css",
    category: "notion",
    subCategory: "boxmodel",
    type: "4지 선다형",
  },
  {
    id: "color",
    title: "색깔",
    author: "색깔",
    topic: "css",
    category: "notion",
    subCategory: "color",
    type: "4지 선다형",
  },
  {
    id: "background",
    title: "배경화면",
    author: "배경화면",
    topic: "css",
    category: "notion",
    subCategory: "background",
    type: "4지 선다형",
  },
  // ... 나머지 퀴즈 항목도 동일하게 수정
];

export const nestjsQuizList = [
  {
    id: "action",
    title: "반응형d",
    author: "반응형d",
    topic: "nestjs",
    category: "code",
    subCategory: "action",
    type: "빈칸 뚫기",
  },
  {
    id: "advance",
    title: "CSS심화d",
    author: "CSS심화d",
    topic: "nestjs",
    category: "code",
    subCategory: "action",
    type: "빈칸 뚫기",
  },
  {
    id: "basic",
    title: "CSS기초d",
    author: "CSS기초d",
    topic: "nestjs",
    category: "code",
    subCategory: "action",
    type: "빈칸 뚫기",
  },
  {
    id: "layout",
    title: "레이아웃d",
    author: "레이아웃d",
    topic: "nestjs",
    category: "code",
    subCategory: "layout",
    type: "빈칸 뚫기",
  },
  {
    id: "background",
    title: "배경화면d",
    author: "배경화면d",
    topic: "nestjs",
    category: "code",
    subCategory: "background",
    type: "빈칸 뚫기",
  },
  {
    id: "style",
    title: "스타일d",
    author: "스타일d",
    topic: "nestjs",
    category: "code",
    subCategory: "style",
    type: "빈칸 뚫기",
  },
  {
    id: "property",
    title: "속성d",
    author: "속성d",
    topic: "nestjs",
    category: "code",
    subCategory: "property",
    type: "빈칸 뚫기",
  },

  // ///////////////////////

  {
    id: "nodeexpress",
    title: "노드익스프레스",
    author: "노드익스프레스",
    topic: "nestjs",
    category: "notion",
    subCategory: "nodeexpress",
    type: "4지 선다형",
  },
  {
    id: "service",
    title: "서비스",
    author: "서비스",
    topic: "nestjs",
    category: "notion",
    subCategory: "service",
    type: "4지 선다형",
  },
  {
    id: "Query_Parameter",
    title: "쿼리 파라미터",
    author: "쿼리 파라미터",
    topic: "nestjs",
    category: "notion",
    subCategory: "Query_Parameter",
    type: "4지 선다형",
  },
  {
    id: "controller",
    title: "컨트롤러",
    author: "컨트롤러",
    topic: "nestjs",
    category: "notion",
    subCategory: "Controller",
    type: "4지 선다형",
  },
  {
    id: "ioc",
    title: "ioc",
    author: "ioc",
    topic: "nestjs",
    category: "notion",
    subCategory: "ioc",
    type: "4지 선다형",
  },
  {
    id: "docker",
    title: "도커",
    author: "도커",
    topic: "nestjs",
    category: "notion",
    subCategory: "docker",
    type: "4지 선다형",
  },

  // ... 나머지 퀴즈 항목도 동일하게 수정
];

export const nestjsImageQuizList = [
  {
    id: "image1",
    title: "이미지 문제 1",
    author: "색깔e",
    image: "/path/to/image1.jpg",
    correctAnswer: "A",
    topic: "nestjs",
    category: "image",
    type: "이미지 문제",
  },
  {
    id: "color",
    title: "색깔ㅇ",
    author: "색깔d",
    image: "/path/to/image1.jpg",
    topic: "nestjs",
    category: "image",
    subCategory: "color",
    type: "이미지 문제",
  },
  // 이하 생략
];
